# Test project

##### What is the project about:
This is a test project for applying to the real project.
In this project was impelented different scrollviews and custom widgets.
One of the screens has buttons for opening web links.  Some of links opens using url launcher with the default device browser, the others opens with the [Web Browser package](https://pub.dev/packages/web_browser).
The poject was implemetted with dart sdk 2.12, with `null-safety sound on`.
Unit tests can't be implemented because there is no busines logic.



